framework:
    messenger:
        # reset services after consuming messages
        reset_on_message: true

        transports:
            complete_callback:
                dsn: "%env(PROFILING_SURVEY_CALLBACK_QUEUE)%"
                options:
                    auto_setup: false
                serializer: messenger.transport.symfony_serializer
            survey_notification:
                dsn: "%env(SURVEY_NOTIFICATION_QUEUE)%"
                options:
                    auto_setup: false
        routing:
            Syno\Storm\Message\ProfilingSurvey: complete_callback
            Syno\Storm\Message\SurveyNotification: survey_notification