services:

    _defaults:
        autowire: true
        autoconfigure: true

    NewRelic\:
        resource: './*'

    NewRelic\Command\DeployCommand:
        arguments:
            $apiKey: '%env(NEW_RELIC_API_KEY)%'
