# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''
    app.available_locales: as|af|am|sq|ar|eu|be|bn|bs|bg|ca|cy|zh_CN|zh_HK|zh_TW|hr|cs|da|nl|nl_NL-informal|en|en_GB|et|fi|fr|gl|de|de_CH|de_AT|de_DE-informal|gu|el|hi|he|hu|is|id|ga|it|it_IT-formal|ja|kn|ko|lt|lv|mk|ms|ml|mt|mr|my_MM|nb|nn|om|or|fa|pl|pt|pt_BR|pa|ru|ro|sk|si|sl|sr|es|es_CL|es_MX|sv|te|ta|tr|th|uk|ur|vi
    app.route_prefix: '/{_locale}'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Syno Storm
    Syno\Storm\:
        resource: '../src/Syno/Storm/*'
        exclude: '../src/Syno/Storm/{DependencyInjection,Entity,Document,Migrations,Tests,Kernel.php,Connection.php}'

    Syno\Storm\Api\Controller\:
        resource: '../src/Syno/Storm/Api/Controller'
        tags: ['controller.service_arguments']

    Syno\Storm\Api\v1\Controller\:
        resource: '../src/Syno/Storm/Api/v1/Controller'
        tags: ['controller.service_arguments']

    Syno\Storm\Api\EventSubscriber\ApiAuthenticationSubscriber:
        arguments:
            $apiAccessToken: '%env(STORM_API_TOKEN)%'

    Syno\Storm\Services\Response:
        arguments:
            $responseIdPrefix: '%env(APP_REGION)%'

    Syno\Cint\Demand\Client:
        class: Syno\Cint\Demand\Client
        factory: '@Cint\Demand\Factories\ClientFactory'
        arguments:
            $apiDomain:  '%env(CINT_DEMAND_API_DOMAIN)%'

imports:
    - { resource: ../src/Cint/services.yaml }