# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Syno Storm
    Syno\Storm\:
        resource: '../src/Syno/Storm/*'
        exclude: '../src/Syno/Storm/{DependencyInjection,Entity,Document,Migrations,Tests,Kernel.php,Connection.php}'

    Syno\Storm\Controller\:
        resource: '../src/Syno/Storm/Controller'
        tags: ['controller.service_arguments']

    Syno\Storm\EventSubscriber\ApiAuthenticationSubscriber:
        arguments:
            $apiAccessToken: '%env(STORM_API_TOKEN)%'
